using Birko.Security.BCrypt.Hashing;
using FluentAssertions;
using Xunit;

namespace Birko.Security.BCrypt.Tests;

/// <summary>
/// CR-H138: reference-vector (known-answer) coverage that round-trip tests cannot provide.
/// The cost-06 vectors are covered by <c>BCryptReferenceVectorTests</c> (added by CR-C24); this
/// class extends known-answer coverage to a second work factor (cost 08) so a regression in the
/// EksBlowfish rounds/cost handling can't hide behind self-consistent hashing.
/// Vectors are canonical jBCrypt / OpenBSD <c>$2a$</c> values generated by an independent library.
/// </summary>
public class BCryptKnownAnswerTests
{
    private readonly BCryptPasswordHasher _hasher = new();

    [Theory]
    [InlineData("", "$2a$08$HqWuK6/Ng6sg9gQzbLrgb.Tl.ZHfXLhvt/SgVyWhQqgqcZ7ZuUtye")]
    public void Verify_AcceptsCanonicalReferenceHash_Cost08(string password, string referenceHash)
    {
        _hasher.Verify(password, referenceHash).Should().BeTrue(
            "the implementation must interoperate with standard OpenBSD $2a$ BCrypt across work factors");
    }

    [Fact]
    public void Verify_RejectsReferenceHash_ForWrongPassword_Cost08()
    {
        _hasher.Verify("wrong", "$2a$08$HqWuK6/Ng6sg9gQzbLrgb.Tl.ZHfXLhvt/SgVyWhQqgqcZ7ZuUtye")
            .Should().BeFalse();
    }
}
